syntax = "proto3";

package com.pda.distributed.network.grpc;

option java_multiple_files = true;

// Mensajes para Unirse a la Red (Mecanismo Semilla)
message JoinRequest {
    string direccion_nodo = 1; // Formato "IP:Puerto" (ej. 127.0.0.1:50052)
    int32 id_nodo = 2;         // Para futuros desempates en elecciones
}

message JoinResponse {
    bool aceptado = 1;
    string anillo_asignado = 2; // "RING_A" o "RING_B"
    string mensaje = 3;
}

// Mensajes para Latidos (Heartbeat/Ping)
message PingRequest {
    string direccion_nodo = 1; // "IP:Puerto" de quien envía el latido
    int32 id_nodo = 2;
}

message PingResponse {
    bool exito = 1;
    string respuesta = 2;
}

// Mensajes para Sincronizar Estado
message PeticionEstado {
    string direccion_origen = 1; // "IP:Puerto" del líder que envía la actualización
    string datos_estado = 2;     // Aquí enviaremos el Map convertido a JSON
}

message RespuestaEstado {
    bool exito = 1;
}

// Mensajes para Votación (Algoritmo Bully)
message PeticionVoto {
    string direccion_candidato = 1; // "IP:Puerto" del que quiere ser líder
    int32 id_candidato = 2;         // CRUCIAL para el desempate del Bully
}

message RespuestaVoto {
    bool acepta = 1;
}

// Mensajes para Subida de Archivos (Chunks)
message PeticionSubida {
    string id_archivo = 1;       // Nombre original del archivo
    int32 indice_fragmento = 2;  // Ej: 0, 1, 2...
    int32 total_fragmentos = 3;  // Total de chunks esperados. Facilita el ensamblaje.
    bytes fragmento = 4;         // Los datos binarios
}

message RespuestaSubida {
    bool exito = 1;
}

message PeticionMetricas {
    string direccion_origen = 1;
}

message RespuestaMetricas {
    int32 id_nodo = 1;
    int64 espacio_libre_bytes = 2;
}

// --- Servicio Principal del Nodo ---
service PdaService {
    // Descubrimiento y conexión inicial
    rpc join(JoinRequest) returns (JoinResponse) {}

    // Mantenimiento de la red
    rpc heartbeat(PingRequest) returns (PingResponse) {}

    // Consenso y Estado
    rpc sincronizarEstado(PeticionEstado) returns (RespuestaEstado) {}
    rpc votar(PeticionVoto) returns (RespuestaVoto) {}

    // Transferencia de datos
    rpc subirFragmento(PeticionSubida) returns (RespuestaSubida) {}

    // Metricas
    rpc obtenerMetricas(PeticionMetricas) returns (RespuestaMetricas) {}
}